### ISSUE TITLE
"Individual AFD's" should probably sort by "Date" column

### ISSUE THREAD

**Issue by NovemLinguae** [APerson241/afdstats#21] opened 2023-06-28 20:23 UTC
Whatever "Individual AFD's" is sorted by is pretty close to what is displaying in the "Date" column, but is slightly different somehow. I think it'd be more intuitive if the sort matched the "Date" column.

<img width="727" alt="image" src="https://github.com/enterprisey/afdstats/assets/79697282/8c433e93-8915-4c99-a940-21e997abf7b0">

**Comment by pppery** [comment] 2023-10-28 00:47
Duplicate of #15

**Closed as not planned** 2023-10-28 00:48 UTC
